[package]
name = "strede-bincode"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
description = "Bincode format backend for strede"
readme = "README.md"

[dependencies]
strede = { path = "../strede", version = "=0.2.3", default-features = false }

[features]
std = ["strede/std", "alloc"]
alloc = ["strede/alloc"]

[dev-dependencies]
strede-derive = { path = "../strede-derive", version = "=0.2.3", features = ["alloc"], default-features = false }
strede-test-util = { path = "../strede-test-util" }
